#!/usr/bin/env bash
# ci-report.sh — Reads ci-results.json and creates a draft PR (fixes applied)
# or a GitHub Issue (unfixed failures). Called by the GitHub Actions workflow.
set -euo pipefail

RESULTS_FILE="ci-results.json"

if [ ! -f "$RESULTS_FILE" ]; then
  echo "No $RESULTS_FILE found — nothing to report."
  exit 0
fi

FIXES_APPLIED=$(jq -r '.fixesApplied' "$RESULTS_FILE")
TESTS_FAILED=$(jq -r '.testsFailed' "$RESULTS_FILE")
TIMESTAMP=$(jq -r '.timestamp' "$RESULTS_FILE")
DATE_SHORT=$(date +%Y-%m-%d)

# Build failure summary from the results JSON
build_summary() {
  local section="$1"  # specsFixed or specsUnfixed
  local label="$2"
  local count
  count=$(jq -r ".$section | length" "$RESULTS_FILE")

  if [ "$count" -eq 0 ]; then
    return
  fi

  echo "### $label ($count)"
  echo ""
  jq -r ".$section[] | \"- **\(.spec)**: \(.error // \"unknown error\" | split(\"\n\") | first)\"" "$RESULTS_FILE"
  echo ""
}

# ── Path A: Fixes were applied → create draft PR ──
if [ "$FIXES_APPLIED" = "true" ]; then
  BRANCH_NAME="auto-fix/regression-${DATE_SHORT}-$(date +%H%M)"

  echo "Creating branch: $BRANCH_NAME"
  git config user.name "github-actions[bot]"
  git config user.email "github-actions[bot]@users.noreply.github.com"
  git checkout -b "$BRANCH_NAME"
  git add cypress/e2e/*.cy.js
  git commit -m "fix(ci): auto-heal failing regression tests — $DATE_SHORT"
  git push -u origin "$BRANCH_NAME"

  PR_BODY=$(cat <<EOF
## Regression Auto-Fix — $DATE_SHORT

The nightly regression run detected test failures. The AI fixer successfully healed them.

**Please review these changes before merging** — the LLM may have "fixed" a test to match
broken app behavior instead of catching a real bug.

$(build_summary specsFixed "Specs Fixed")
$(build_summary specsUnfixed "Specs Still Failing")

### What to check
- [ ] Are the test changes correct, or is the app behavior wrong?
- [ ] Do the assertions still validate the intended user flow?
- [ ] Run the affected specs locally to confirm

---
*Generated by the SDET Multi-Agent Pipeline CI at $TIMESTAMP*
EOF
)

  gh pr create \
    --draft \
    --title "Auto-fix: regression test failures $DATE_SHORT" \
    --body "$PR_BODY"

  echo "Draft PR created successfully."
fi

# ── Path B: Unfixed failures remain → create GitHub Issue ──
if [ "$TESTS_FAILED" -gt 0 ]; then
  ISSUE_BODY=$(cat <<EOF
## Regression Failures — $DATE_SHORT

The nightly regression run found test failures that the AI fixer could not resolve
after 3 attempts per spec.

$(build_summary specsUnfixed "Unfixed Failures")
$(build_summary specsFixed "Specs That Were Fixed")

### Next steps
- [ ] Investigate root cause — is this a test issue or an app change?
- [ ] Check Cypress screenshots in the CI artifacts
- [ ] Fix manually or update the test expectations

---
*Generated by the SDET Multi-Agent Pipeline CI at $TIMESTAMP*
EOF
)

  gh issue create \
    --title "Regression failures: $DATE_SHORT" \
    --body "$ISSUE_BODY" \
    --label "bug,automated"

  echo "GitHub Issue created for unfixed failures."
fi
